### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: this.message is not a function

### ISSUE THREAD

**Issue by FellGill** [TheDrone7/disco-oauth#1]
(node:11032) UnhandledPromiseRejectionWarning: TypeError: this.message is not a function
    at new ParamError (~~~\node_modules\disco-oauth\src\Constants\errors.js:11:14)
    at Promise (~~~\node_modules\disco-oauth\src\client.js:249:24)
    at new Promise (<anonymous>)
    at DiscordClient.getAuthorizedUser (~~~\node_modules\disco-oauth\src\client.js:223:16)
    at ~~~\app.js:85:42
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by TheDrone7** [comment]
Could you provide more info please, this is insufficient, like what are you trying to do? What's your code?

**Comment by TheDrone7** [comment]
I'll close this issue now because of no reply, please open a new issue if the problem persists. Although I believe it might be due to improper implementation. Please upgrade to v3.0.1 as well.
