### ISSUE TITLE
TypeError: i.toLowerCase is not a function | Help

### ISSUE THREAD

**Issue by Sandessat** [TheDrone7/disco-oauth#13]
/rbd/pnpm-volume/6b1a1f04-bb1c-4773-86c2-6fe6a065ca83/node_modules/.registry.npmjs.org/disco-oauth/4.2.1/node_modules/disco-oauth/lib/client.js:49
        if (scopesList.includes(i.toLowerCase().trim())) {
                                  ^
TypeError: i.toLowerCase is not a function
    at Client.setScopes (/rbd/pnpm-volume/6b1a1f04-bb1c-4773-86c2-6fe6a065ca83/node_modules/.registry.npmjs.org/disco-oauth/4.2.1/node_modules/disco-oauth/lib/client.js:49:35)
at Object.<anonymous> (/app/server.js:36:13)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:826:10)
    at internal/main/run_main_module.js:17:11

**Comment by TheDrone7** [comment]
Refer to the docs at https://disco-oauth.tk this is not a bug.
