### ISSUE TITLE
SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by djilano** [TheDrone7/disco-oauth#17]
`const oauthClient = new OAuthClient('ClientID', 'secretKey')`

Will result in:

```E:\Projecten\Personal\graphite\node_modules\disco-oauth\lib\types\user.js:92
    return parseInt(BigInt('0b' + parseInt(this._id).toString(2)) >> 22n) + 1420070400000;
                                                                     ^^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\Projecten\Personal\graphite\node_modules\disco-oauth\lib\client.js:3:14)
[nodemon] app crashed - waiting for file changes before starting...```

**Comment by TheDrone7** [comment]
Provide more details, try following the issue template.
