### ISSUE TITLE
Invalid scope provided.

### ISSUE THREAD

**Issue by Cat4eve** [TheDrone7/disco-oauth#50]
I don't understand what is wrong. I have three files - discordOAuthClient.js, discordOAuth.js and config.json.

**discordOAuthClient.js**
```js
const OAuthClient = require('disco-oauth');

module.exports = class DiscordOAuthClient {
    constructor(clientId, clientSecret, scopes, redirectUri) {
        this.clientId = String(clientId);
        this.clientSecret = clientSecret;
        this.scopes = scopes
        this.redirectUri = redirectUri;

        this.setClient();
        this.setScopes();
        this.setRedirect();
    }

    setClient() {
        this.client = new OAuthClient(this.clientId, this.clientSecret);
    }

    setScopes() {
        if (typeof this.scopes == 'string') {
            this.client.setScopes(this.scopes);
        } else if (this.scopes.isArray()) {
            this.scopes = this.scopes.join(' ');
            this.client.setScopes(this.scopes);
        }
    }

    setRedirect() {
        this.client.setRedirect(this.redirectUri);
    }

    async getAccessToken(code) {
        return await this.client.getAccess(code);
    }

    async refreshAccessToken(token) {
        return await this.client.refreshToken(token);
    }

    async getUser(token) {
        if (!this.scopes.split(" ").includes('identify')) throw new Error("Wrong scopes.")
        return await this.client.getUser(token);
    }

    async getGuilds(token) {
        if (!this.scopes.split(" ").includes('guilds')) throw new Error("Wrong scopes.")
        return await this.client.getGuilds(token);
    }

    async getConnections(token) {
        if (!this.scopes.split(" ").includes('connections')) throw new Error("Wrong scopes.")
        return await this.client.getConnections(token);
    }
}
```

**discordOAuth.js**
```js
const RouteModel = require('./routeModel');
const { WSEvent } = require('../events');
const DiscordOAuthClient = require('../discordOAuthClient');
const { bot_configuration } = require('../config.json');

const discordOAuthClient = new DiscordOAuthClient(clientId = bot_configuration.client_id, clientSecret = bot_configuration.client_secret, scopes = bot_configuration.scope, redirectUri = bot_configuration.redirect_uri);


const echoRoute = new RouteModel(endpoint = '/discordOuath', functionality = async (msg) => {
    const msgObject = RouteModel.decode(msg);
    switch (msgObject.e) {
        case WSEvent.AUTH:
            if (!msgObject.d.c) break;
            await discordOAuthClient.getAccessToken(msgObject.d.c);
    }
});

module.exports = echoRoute;
```

**config.json**
```js
{
    "bot_configuration": {
        "client_id": "secret",
        "client_secret": "secret",
        "scope": "identify connection guilds",
        "redirect_uri": "http://localhost:4200/auth/login",
        "base_url": "https://discord.com/api/",
        "api_version": "7",
        "token_endpoint": "/oauth2/token/"
    },

    "port": 3000,
    "route_configurator_name": "routeConfigurator"
}
//some of these are not used and it's okey!
```

What I get is this error.
```
C:\Users\karap\node_modules\disco-oauth\lib\client.js:80
      if (!scopesList.includes(scope)) throw new Error('Invalid scope provided.');
                                       ^

Error: Invalid scope provided.
    at Client.setScopes (C:\Users\karap\node_modules\disco-oauth\lib\client.js:80:46)
    at DiscordOAuthClient.setScopes (C:\Users\karap\Desktop\WebSite\back-end\discordOAuthClient.js:21:25)
    at new DiscordOAuthClient (C:\Users\karap\Desktop\WebSite\back-end\discordOAuthClient.js:11:14)
    at Object.<anonymous> (C:\Users\karap\Desktop\WebSite\back-end\routes\discordOAuth.js:6:28)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
PS C:\Users\karap\Desktop\WebSite\back-end> 
```

**Comment by TheDrone7** [comment]
`Client.scopes` is supposed to be an array, not a string. It's not a bug, PLEASE use the discussions for this kind of thing.

Refer to the docs for more details - https://disco-oauth.tk/docs/5.1.1/client
